### ISSUE TITLE
Update the map rotation

### ISSUE THREAD

**Issue by BigCTheYeti** [The-Purgery/The-Purgery#19] opened 2024-06-16 02:46 UTC
remove unplayed or pointless maps like campgrounds blue, gridworks, delerium, wintersedge etc. from regular map rotation
add some often-voted favourites to map rotation e.g. ts_ca1, uprise, swift, q3wsh22(?) and so on

**Comment by meganfoxxed** [comment] 2024-06-16 05:51
Purger will be working on this in a way it we be exposed to some of the admins and something we can look at doing . See #9 for more details

**Comment by tjone270** [comment] 2024-06-16 07:03
Duplicate of #13 however as per @meganfoxxed comment we will be exposing this at a moderator level.

**Closed as completed by tjone270** 2024-06-16 07:03 UTC
Labels: wontfix
